# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studnet_grade',
            new_name='student_grade',
        ),
    ]
