# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0002_auto_20160415_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_student',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='problem_student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='problem_student',
            name='problem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydb.Problem'),
        ),
        migrations.AddField(
            model_name='problem_student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mydb.Student'),
        ),
    ]
