# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0003_auto_20160416_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_student',
            name='problem_student_review',
            field=models.TextField(null=True),
        ),
    ]
