# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0007_auto_20160417_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_student',
            name='problem_student_spendspace',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem_student',
            name='problem_student_spendtime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem_student',
            name='problem_student_submittime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
